In [23]:
import numpy as np

In [24]:
arr = np.random.randint(1, 100, size=(10,5))
arr.shape

(10, 5)

In [26]:
b = arr.reshape(5, 10)
x = arr.reshape(2, 25) # can't re shape

# print(x)
# b.shape
# b.ndim
flatten = b.flatten()
print(flatten)
# flatten.ndim

[52 70 79 46 12 64 52 64 11  5 22 47 41 82 33 91 70 66 23 89 22 67 88 90
 85 59 66 61 95 21 49 19 86 74 71 71 78  1 43  9  3 12 50 93 41 65 68 31
 14 83]


In [27]:
b

array([[52, 70, 79, 46, 12, 64, 52, 64, 11,  5],
       [22, 47, 41, 82, 33, 91, 70, 66, 23, 89],
       [22, 67, 88, 90, 85, 59, 66, 61, 95, 21],
       [49, 19, 86, 74, 71, 71, 78,  1, 43,  9],
       [ 3, 12, 50, 93, 41, 65, 68, 31, 14, 83]], dtype=int32)

In [30]:
column_flatten = np.ravel(b, order='F')
column_flatten

array([52, 22, 22, 49,  3, 70, 47, 67, 19, 12, 79, 41, 88, 86, 50, 46, 82,
       90, 74, 93, 12, 33, 85, 71, 41, 64, 91, 59, 71, 65, 52, 70, 66, 78,
       68, 64, 66, 61,  1, 31, 11, 23, 95, 43, 14,  5, 89, 21,  9, 83],
      dtype=int32)

In [ ]:
a = np.random.randint(1, 10, size=(2,3))
b = np.random.randint(20, 30, size=(2,3))
print(a)
print(b)

print(a + b)

[[3 6 8]
 [4 8 3]]
[[20 23 24]
 [25 29 29]]
