In [24]:
import numpy as np

In [25]:
arr = np.random.randint(1, 100, size=(10,5))
arr.shape

(10, 5)

In [26]:
b = arr.reshape(5, 10)
x = arr.reshape(2, 25) # can't re shape

# print(x)
# b.shape
# b.ndim
flatten = b.flatten()
print(flatten)
# flatten.ndim

[45 84 17 95 10 16 40 47  5 34 12 35 43 34 79 94 59 18 14 92 88  6 78 27
 15 30 79 69 23 45 53 90 28 17 84 30 40 20 49 58 45 58 86 64  1 78 64 53
  5 20]


In [27]:
b

array([[45, 84, 17, 95, 10, 16, 40, 47,  5, 34],
       [12, 35, 43, 34, 79, 94, 59, 18, 14, 92],
       [88,  6, 78, 27, 15, 30, 79, 69, 23, 45],
       [53, 90, 28, 17, 84, 30, 40, 20, 49, 58],
       [45, 58, 86, 64,  1, 78, 64, 53,  5, 20]], dtype=int32)

In [28]:
column_flatten = np.ravel(b, order='F')
column_flatten

array([45, 12, 88, 53, 45, 84, 35,  6, 90, 58, 17, 43, 78, 28, 86, 95, 34,
       27, 17, 64, 10, 79, 15, 84,  1, 16, 94, 30, 30, 78, 40, 59, 79, 40,
       64, 47, 18, 69, 20, 53,  5, 14, 23, 49,  5, 34, 92, 45, 58, 20],
      dtype=int32)

In [29]:
a = np.random.randint(1, 10, size=(3,3))
b = np.random.randint(20, 30, size=(1,3))

print(a)
print(b)

con = np.concatenate((a, b), axis=0)
print(con)

[[9 8 2]
 [6 1 4]
 [7 5 9]]
[[28 20 25]]
[[ 9  8  2]
 [ 6  1  4]
 [ 7  5  9]
 [28 20 25]]


In [ ]:
arr = np.array([[1,2,3,4],
                [9,8,7,6]])

print(arr.shape)
print(arr.ndim)
print(arr)


(2, 4)
2
[[1 2 3 4]
 [9 8 7 6]]
[[1 2]
 [3 4]
 [9 8]
 [7 6]]
