In [343]:
import numpy as np

In [344]:
a = np.array([1,2,3])
b = np.array([4,5.4,6])
c = np.array(['nafiz', 3, 4.4, True])


print(a)
print(b)
print(a + b)


[1 2 3]
[4.  5.4 6. ]
[5.  7.4 9. ]


In [345]:
oned = np.array([1,2,3])

twod = np.array([
    [1,2,3],
    [4,5,6]
])

threed = np.array([
    [[1,2,3], [4,5,6]],
    [[1,2,3], [4,5,6]],
    [[1,2,3], [4,5,6]]
])

In [346]:
print(oned)


[1 2 3]


In [347]:
print(twod)


[[1 2 3]
 [4 5 6]]


In [348]:
print(threed)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [349]:
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)



1
2
3


In [350]:
print(oned.dtype)
print(twod.dtype)
print(threed.dtype)



int64
int64
int64


In [351]:
print(oned.size)
print(twod.size)
print(threed.size)



3
6
18


In [352]:
print(b.dtype)

float64


In [353]:
print(c.dtype)

<U32


In [354]:
setted_npdata = np.array([1,2,'3'], dtype=np.float64)
print(setted_npdata.dtype)

setted_npdata_cpy = setted_npdata.astype(np.int32)
print(setted_npdata_cpy.dtype)


float64
int32


In [355]:
lst = [1,2,3,45]
nplst = np.array(lst)
print(type(lst))
print(type(nplst.dtype))

<class 'list'>
<class 'numpy.dtypes.Int64DType'>


In [356]:
matrix = [
    [1,2,3],
    [4,5,6]
]

arr_matrix = np.array(matrix, dtype=np.float32)
print(matrix)
print(arr_matrix)

print(type(matrix))
print(arr_matrix.ndim)
print(arr_matrix.shape)



[[1, 2, 3], [4, 5, 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
<class 'list'>
2
(2, 3)


In [357]:
st = {1,2,3}
st_array = np.array(list(st))

print(st_array.dtype)
print(st_array.ndim)
print(st_array.shape)
print(st_array.size)



int64
1
(3,)
3


In [358]:
dick = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
print(dick)
print(type(dick))

array_dick1 = np.array(list(dick.keys()))
array_dick2 = np.array(list(dick.values()))
array_dick3 = np.array(list(dick.items()))

print(array_dick1)
print(array_dick2)
print(array_dick3)

print(array_dick1.ndim)
print(array_dick2.ndim)
print(array_dick3.ndim)

print(array_dick1.size)
print(array_dick2.size)
print(array_dick3.size)

print(array_dick3.dtype)
print(array_dick2.dtype)
print(array_dick1.dtype)


{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
<class 'dict'>
['a' 'b' 'c' 'd' 'e']
[1 2 3 4 5]
[['a' '1']
 ['b' '2']
 ['c' '3']
 ['d' '4']
 ['e' '5']]
1
1
2
5
5
10
<U21
int64
<U1


In [359]:
arr = np.zeros((3,3))
arr = arr.astype(np.int16)

print(arr)
print(arr.dtype)

arr2 = np.zeros_like(arr)
print(arr2)
print(arr2.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int16
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int16


In [360]:
arr = np.ones((3,3), dtype=np.int16)
print(arr)

arr2 = np.ones_like(arr)
print(arr2)
print(arr2.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
int16


In [361]:
arr = np.empty((3,3), dtype=np.int8)
print(arr)

arr2 = np.empty_like(arr)
print(arr2)
print(arr2.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int8


In [362]:
arr = np.full((3,3), fill_value=1)
arr2 = np.full((3,3), np.inf)

print(arr)
print(arr2)


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [363]:
arr = np.full((3,3), np.inf)
print(arr)
arr2 = np.full_like(arr, np.inf, dtype=np.float32)
print(arr2)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [364]:
arr = np.random.rand(3,3)
print(arr)


[[0.12906115 0.93561128 0.74086765]
 [0.53159081 0.70921762 0.46658734]
 [0.90948823 0.89947078 0.91842874]]


In [365]:
arr = np.random.randint(1, 10, (3, 3, 3))
print(arr)

[[[3 6 1]
  [4 1 1]
  [4 9 5]]

 [[5 3 3]
  [7 4 9]
  [6 4 2]]

 [[4 7 4]
  [6 6 8]
  [8 6 1]]]


In [366]:
arr = np.random.uniform(1,5, (3,3,3))
print(arr)

[[[3.405197   4.91915808 2.21895133]
  [2.39980867 4.05202325 3.51743124]
  [1.43413473 3.01588894 2.66972124]]

 [[4.77265871 1.27633225 4.67738876]
  [4.60714793 2.35197313 2.36193509]
  [4.62755471 1.18445832 2.28565169]]

 [[3.62663438 3.94108066 2.27327872]
  [1.53458837 3.22227873 1.1454029 ]
  [1.53307982 2.03987526 3.80170745]]]


In [369]:
arr = np.arange(1,17)
print(arr)

reshape_arr = arr.reshape(4,4)
print(reshape_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [374]:
arr = np.linspace(1,2,5, dtype=np.float32)
print(arr)

[1.   1.25 1.5  1.75 2.  ]


In [384]:
arr = np.logspace(10,20,5,base=1000)
print(arr)

[1.00000000e+30 3.16227766e+37 1.00000000e+45 3.16227766e+52
 1.00000000e+60]
