In [90]:
import numpy as np

In [91]:
a = np.array([1,2,3])
b = np.array([4,5.4,6])
c = np.array(['nafiz', 3, 4.4, True])


print(a)
print(b)
print(a + b)


[1 2 3]
[4.  5.4 6. ]
[5.  7.4 9. ]


In [92]:
oned = np.array([1,2,3])

twod = np.array([
    [1,2,3],
    [4,5,6]
])

threed = np.array([
    [[1,2,3], [4,5,6]],
    [[1,2,3], [4,5,6]],
    [[1,2,3], [4,5,6]]
])

In [93]:
print(oned)


[1 2 3]


In [94]:
print(twod)


[[1 2 3]
 [4 5 6]]


In [95]:
print(threed)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [96]:
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)



1
2
3


In [97]:
print(oned.dtype)
print(twod.dtype)
print(threed.dtype)



int64
int64
int64


In [98]:
print(oned.size)
print(twod.size)
print(threed.size)



3
6
18


In [99]:
print(b.dtype)

float64


In [100]:
print(c.dtype)

<U32


In [101]:
setted_npdata = np.array([1,2,'3'], dtype=np.float64)
print(setted_npdata.dtype)

setted_npdata_cpy = setted_npdata.astype(np.int32)
print(setted_npdata_cpy.dtype)


float64
int32


In [102]:
lst = [1,2,3,45]
nplst = np.array(lst)
print(type(lst))
print(type(nplst.dtype))

<class 'list'>
<class 'numpy.dtypes.Int64DType'>


In [109]:
matrix = [
    [1,2,3],
    [4,5,6]
]

arr_matrix = np.array(matrix, dtype=np.float32)
print(matrix)
print(arr_matrix)

print(type(matrix))
print(arr_matrix.ndim)
print(arr_matrix.shape)



[[1, 2, 3], [4, 5, 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
<class 'list'>
2
(2, 3)


In [112]:
st = {1,2,3}
st_array = np.array(list(st))

print(st_array.dtype)
print(st_array.ndim)
print(st_array.shape)
print(st_array.size)



int64
1
(3,)
3


In [ ]:
dic