In [321]:
import numpy as np

In [322]:
a = np.array([1,2,3])
b = np.array([4,5.4,6])
c = np.array(['nafiz', 3, 4.4, True])


print(a)
print(b)
print(a + b)


[1 2 3]
[4.  5.4 6. ]
[5.  7.4 9. ]


In [323]:
oned = np.array([1,2,3])

twod = np.array([
    [1,2,3],
    [4,5,6]
])

threed = np.array([
    [[1,2,3], [4,5,6]],
    [[1,2,3], [4,5,6]],
    [[1,2,3], [4,5,6]]
])

In [324]:
print(oned)


[1 2 3]


In [325]:
print(twod)


[[1 2 3]
 [4 5 6]]


In [326]:
print(threed)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [327]:
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)



1
2
3


In [328]:
print(oned.dtype)
print(twod.dtype)
print(threed.dtype)



int64
int64
int64


In [329]:
print(oned.size)
print(twod.size)
print(threed.size)



3
6
18


In [330]:
print(b.dtype)

float64


In [331]:
print(c.dtype)

<U32


In [332]:
setted_npdata = np.array([1,2,'3'], dtype=np.float64)
print(setted_npdata.dtype)

setted_npdata_cpy = setted_npdata.astype(np.int32)
print(setted_npdata_cpy.dtype)


float64
int32


In [333]:
lst = [1,2,3,45]
nplst = np.array(lst)
print(type(lst))
print(type(nplst.dtype))

<class 'list'>
<class 'numpy.dtypes.Int64DType'>


In [334]:
matrix = [
    [1,2,3],
    [4,5,6]
]

arr_matrix = np.array(matrix, dtype=np.float32)
print(matrix)
print(arr_matrix)

print(type(matrix))
print(arr_matrix.ndim)
print(arr_matrix.shape)



[[1, 2, 3], [4, 5, 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
<class 'list'>
2
(2, 3)


In [335]:
st = {1,2,3}
st_array = np.array(list(st))

print(st_array.dtype)
print(st_array.ndim)
print(st_array.shape)
print(st_array.size)



int64
1
(3,)
3


In [336]:
dick = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
print(dick)
print(type(dick))

array_dick1 = np.array(list(dick.keys()))
array_dick2 = np.array(list(dick.values()))
array_dick3 = np.array(list(dick.items()))

print(array_dick1)
print(array_dick2)
print(array_dick3)

print(array_dick1.ndim)
print(array_dick2.ndim)
print(array_dick3.ndim)

print(array_dick1.size)
print(array_dick2.size)
print(array_dick3.size)

print(array_dick3.dtype)
print(array_dick2.dtype)
print(array_dick1.dtype)


{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
<class 'dict'>
['a' 'b' 'c' 'd' 'e']
[1 2 3 4 5]
[['a' '1']
 ['b' '2']
 ['c' '3']
 ['d' '4']
 ['e' '5']]
1
1
2
5
5
10
<U21
int64
<U1


In [337]:
arr = np.zeros((3,3))
arr = arr.astype(np.int16)

print(arr)
print(arr.dtype)

arr2 = np.zeros_like(arr)
print(arr2)
print(arr2.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int16
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int16


In [338]:
arr = np.ones((3,3), dtype=np.int16)
print(arr)

arr2 = np.ones_like(arr)
print(arr2)
print(arr2.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
int16


In [339]:
arr = np.empty((3,3), dtype=np.int8)
print(arr)

arr2 = np.empty_like(arr)
print(arr2)
print(arr2.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
int8


In [340]:
arr = np.full((3,3), fill_value=1)
arr2 = np.full((3,3), np.inf)

print(arr)
print(arr2)


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [341]:
arr = np.full((3,3), np.inf)
print(arr)
arr2 = np.full_like(arr, np.inf, dtype=np.float32)
print(arr2)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [342]:
arr = np.random.rand(3,3)
print(arr)


[[0.04218952 0.16401781 0.96399527]
 [0.12139216 0.50206287 0.744662  ]
 [0.15724047 0.30852027 0.59985268]]


In [343]:
arr = np.random.randint(1, 10, (3, 3, 3))
print(arr)

[[[4 8 9]
  [5 6 3]
  [5 1 7]]

 [[1 3 6]
  [9 7 5]
  [7 6 7]]

 [[2 1 9]
  [8 5 1]
  [1 5 6]]]


In [344]:
arr = np.random.uniform(1,5, (3,3,3))
print(arr)

[[[1.15843452 2.81343133 2.28510146]
  [3.58411971 3.16336723 1.60492145]
  [1.44329217 2.87622692 1.36239414]]

 [[2.42535892 2.47553084 4.33181668]
  [3.9396219  1.63180713 2.91707359]
  [2.90276653 4.15180043 1.15998909]]

 [[2.43917334 2.03662381 3.16357614]
  [3.57325305 2.2813871  3.70788427]
  [4.58758057 2.13276775 4.36823005]]]


In [345]:
arr = np.arange(1,17)
print(arr)

reshape_arr = arr.reshape(4,4)
print(reshape_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [346]:
arr = np.linspace(1,2,5, dtype=np.float32)
print(arr)

[1.   1.25 1.5  1.75 2.  ]


In [347]:
arr = np.logspace(10,20,5,base=1000)
print(arr)

[1.00000000e+30 3.16227766e+37 1.00000000e+45 3.16227766e+52
 1.00000000e+60]


In [348]:
diad_mattrix = np.diag([1,2,1,2])
print(diad_mattrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 2]]


In [349]:
identity_matrix = np.eye(4)
print(identity_matrix)

identity_matrix = np.eye(3,2)
print(identity_matrix)

identity_matrix = np.eye(4,5,1)
print(identity_matrix)

identity_matrix = np.eye(4,4,-2)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [350]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

In [351]:
print(arr1)
print(arr2)


[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [352]:
arr1[2] = 100
print(arr1)

arr2[1][2] = 100
print(arr1)

[  1   2 100   4]
[  1   2 100   4]


In [353]:
print(arr1)
print(arr2)

[  1   2 100   4]
[[  1   2   3]
 [  4   5 100]]


In [354]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

In [355]:
print(arr2[1:2])


[[4 5 6]]


In [356]:
print(arr2[:,0:2])

[[1 2]
 [4 5]]


In [357]:
lst = np.array([1,2,30,4,50])
lst_of_lst = lst[[0,1,4]]
print(lst)
print(lst_of_lst)



[ 1  2 30  4 50]
[ 1  2 50]


In [358]:
arr = np.array([
    [7, 2, 3, 3],
 [3, 6, 3, 5],
 [2, 7, 5, 2]
])
# print(arr)
print(arr[[0,1], [1,3]])
arr[arr < 0] = 402
print(arr)
print(arr[arr > 4])

[2 5]
[[7 2 3 3]
 [3 6 3 5]
 [2 7 5 2]]
[7 6 5 7 5]


In [359]:
iter_arr = np.array([
    [[1, 2, 3],
  [4, 5, 6]],
 [[7, 8, 9],
  [10, 11, 12]]
])
print(iter_arr.ndim)

for i in np.nditer(iter_arr):
  print(i, end=" ")

3
1 2 3 4 5 6 7 8 9 10 11 12 

In [360]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

arr_reshape = arr.reshape(2,3)
print(arr_reshape)

(6,)
[[1 2 3]
 [4 5 6]]


In [361]:
arr = np.arange(6)
arr2 = arr.reshape(3, 2)
print(arr2)

arr.resize(2, 3)
print(arr)


[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [362]:
arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)
flat1 = arr.flatten()
flat2 = arr.ravel()
print("Flatten result:", flat1, type(flat1), flat1.ndim, flat1.dtype)
print("Ravel result:", flat2, type(flat2), flat2.ndim, flat2.dtype)


2
Flatten result: [1 2 3 4] <class 'numpy.ndarray'> 1 int64
Ravel result: [1 2 3 4] <class 'numpy.ndarray'> 1 int64


In [363]:
arr = np.array([[10, 20], [30, 40]])
r = arr.flatten()
r[0] = 999
print("Modified flatten array:", r)
print("Original array also changes:", arr)


Modified flatten array: [999  20  30  40]
Original array also changes: [[10 20]
 [30 40]]


In [364]:
arr = np.array([[10, 20], [30, 40]])
r = arr.ravel()
r[0] = 999
print("Modified ravel array:", r)
print("Original array also changes:", arr)


Modified ravel array: [999  20  30  40]
Original array also changes: [[999  20]
 [ 30  40]]


In [367]:
arr = np.array([1, 2, 3])
print(arr.shape)

expanded = np.expand_dims(arr, axis=0)
print(expanded.shape)

arr = np.squeeze(arr)
print(arr.shape)

expanded1 = np.expand_dims(arr, axis=1)
print(expanded1.shape)

arr = np.squeeze(arr)
print(arr.shape)

(3,)
(1, 3)
(3,)
(3, 1)
(3,)
