In [4]:
# main implementation
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4
        print(f"Self.weights {self.weights}")
        self.eta = eta
        self.epochs = epochs

    def activationFunction(self, inputs, weights):
        z = np.dot(inputs, weights)
        return np.where(z>0, 1, 0)
        

    def fit(self, x, y):
        self.x=x
        self.y=y

        x_with_bias = np.c_[self.x, -np.ones((len(self.x), 1))]
        print(f"x with bias {x_with_bias}")


        for epoch in range(self.epochs):
            print(f"epoch : {self.epochs}")

            y_hat = self.activationFunction(x_with_bias, self.weights)
            print(f"predicted value {y_hat}")

            error = self.y - y_hat
            print(f"Error : {error}")

            # weight update
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T, error)
            print(f"updated weights {self.weights}")

def predict(self, x):
    x_with_bias  = np.c_[x, -np.ones((len(x), 1))]
    return self.activationFunction(x_with_bias, self.weights)





In [5]:
data = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1]
}
AND = pd.DataFrame(data)
x = AND.drop("y", axis=1)
y = AND["y"]
y.to_frame()

model = Perceptron(eta=0.5, epochs=10)
model.fit(x, y)

Self.weights [1.35860696e-04 8.24711963e-05 6.34119783e-05]
x with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
epoch : 10
predicted value [0 1 1 1]
Error : 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights [-0.49986414 -0.49991753  1.00006341]
epoch : 10
predicted value [0 0 0 0]
Error : 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights [1.35860696e-04 8.24711963e-05 5.00063412e-01]
epoch : 10
predicted value [0 0 0 0]
Error : 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights [5.00135861e-01 5.00082471e-01 6.34119783e-05]
epoch : 10
predicted value [0 1 1 1]
Error : 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights [1.35860696e-04 8.24711963e-05 1.00006341e+00]
epoch : 10
predicted value [0 0 0 0]
Error : 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights [0.50013586 0.50008247 0.50006341]
epoch : 10
predicted value [0 1 1 1]
Error : 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
upd